version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: my_image
    build: .
    ports:
      - "8080:8080"
    links:
      - "dbpostgresql:dbpostgresql"
  dbpostgresql :
    image: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=bayousha
      - POSTGRES_USER=user_1
      - POSTGRES_DB=db1