version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: my_image
    build: Activité1.2.2/Docker-compose.yml
    ports:
      - 8080
    depends_on:
      - dbpostgresql
  dbpostgresql :
    image: postgres
    container_name: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=bayousha
      - POSTGRES_USER=user_1
      - POSTGRES_DB=db1